export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  CLIENTES: '/clientes',
  CLIENTE_NEW: '/clientes/nuevo',
  CLIENTE_DETAIL: (id: string) => `/clientes/${id}`,
  CLIENTE_EDIT: (id: string) => `/clientes/${id}/editar`,
  VEHICULOS: '/vehiculos',
  VEHICULO_NEW: '/vehiculos/nuevo',
  VEHICULO_EDIT: (id: string) => `/vehiculos/${id}/editar`,
  EQUIPOS_GNC: '/equipos-gnc',
  EQUIPO_GNC_NEW: '/equipos-gnc/nuevo',
  EQUIPO_GNC_EDIT: (id: string) => `/equipos-gnc/${id}/editar`,
  ORDENES_TRABAJO: '/ordenes-trabajo',
  ORDEN_TRABAJO_NEW: '/ordenes-trabajo/nuevo',
  ORDEN_TRABAJO_DETAIL: (id: string) => `/ordenes-trabajo/${id}`,
  ORDEN_TRABAJO_EDIT: (id: string) => `/ordenes-trabajo/${id}/editar`,
  INVENTARIO: '/inventario',
  PRODUCTO_NEW: '/inventario/nuevo',
  PRODUCTO_DETAIL: (id: string) => `/inventario/${id}`,
  PRODUCTO_EDIT: (id: string) => `/inventario/${id}/editar`,
  MOVIMIENTO_STOCK: '/inventario/movimiento',
  MOVIMIENTO_STOCK_PRODUCTO: (
    productoId: string,
    params?: { tipo?: 'ingreso' | 'egreso' | 'ajuste' },
  ) => {
    const search = new URLSearchParams({ productoId })
    if (params?.tipo) search.set('tipo', params.tipo)
    return `/inventario/movimiento?${search.toString()}`
  },
  CAJA: '/caja',
  CAJA_MOVIMIENTO_NEW: '/caja/movimiento',
  FACTURACION: '/facturacion',
  FACTURA_NEW: '/facturacion/nueva',
  FACTURA_NEW_FROM_OT: (otId: string) => `/facturacion/nueva?otId=${otId}`,
  FACTURA_NEW_FROM_NC: (facturaId: string) => `/facturacion/nueva?ncDesde=${facturaId}`,
  FACTURA_DETAIL: (id: string) => `/facturacion/${id}`,
  AGENDA: '/agenda',
  TURNO_NEW: '/agenda/nuevo',
  TURNO_EDIT: (id: string) => `/agenda/${id}/editar`,
  CONFIGURACION: '/configuracion',
  CONFIG_USUARIOS: '/configuracion/usuarios',
  CONFIG_USUARIO_NEW: '/configuracion/usuarios/nuevo',
  CONFIG_USUARIO_EDIT: (id: string) => `/configuracion/usuarios/${id}/editar`,
  CONFIG_MARCAS_MODELOS: '/configuracion/marcas-modelos',
  CONFIG_CATEGORIAS: '/configuracion/categorias',
  CONFIG_KITS: '/configuracion/kits-trabajo',
} as const

export type RouteKey = keyof typeof ROUTES
